Feature
Oxford-G/mobile-menu pull request #1
Opened 2022-02-03 12:24 UTC by Oxford-G

In this project, I added a mobile menu for small screens.

2022-02-04 15:30 UTC, mahbubul14 requested changes
# STATUS: REQUIRED CHANGES ♻️

Hi @Oxford-G , 

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

- [ ] Add a descriptive README file to your project - please use this [template](https://github.com/microverseinc/readme-template) but remember to customize it to your project

- [ ] Check the comments under the review. :arrow_down: 

### Optional suggestions:

- [ ]  Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

- [ ]  Please can you try to see if we can start giving descriptive branch names while working so that anyone can easily know what that created branch is all about
For instance: mobile-menu instead of the feature.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. Also you can reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-02-04 15:30 UTC, mahbubul14 commented on css/main.css
> +} */
- [ ] The close button is missing from the mobile menu. This could be because a .closebtn class that is present in the CSS is missing in your .html file. Please work on that.
* Your page looks like now:
![](https://user-images.githubusercontent.com/36844547/139728860-7d2b1130-7c51-4803-8fc1-a930a5ea720d.png)
* This should look like this:
![](https://user-images.githubusercontent.com/36844547/139729533-61cfc3a1-d952-45ae-addb-965bf9113ce1.png)

- [ ] Kindly remove the commented code if is not necessary. It always makes your code cleaner. :+1:

2022-02-05 17:02 UTC, nicupop729 requested changes
Hi @Oxford-G, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️

- [ ] I appreciate you updated the README file. But it is not yet looking professional and is providing misleading information. 
         Please update the README with:
         -  provide the right title;
         -  provide a good description;
         - remove the MIT explanation from README as you should have it in your MIT file;
         - provide indications to users on how to replicate your project on their local machine;

- [ ] As the previous CR mentioned, please take into account to remove the commented code from your CSS file;

- [ ] For the rest of the required changes, please _Check the comments under the review._ and check the Optional suggestions

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ ] As it was not asked by the previous reviewer, I will leave this as optional, but it is strongly recommended to take action and change it - it is a reason to invalidate your PR:
**Your linters are incomplete, lighthouse and webhint linters are missing from your linters.yml file**

- [ ] As the previous CR suggested, it is important to name our branch with descriptive names. In this case could be: `mobile-menu-nav`.

- [ ] You can take into account updating the MIT file too with the correct information, as for now it is not completed.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-05 17:02 UTC, nicupop729 commented on index.js
> +closeNav();
In order to respect the project requirements, it is important to make sure that:

- [ ] When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed.

- [ ] When the user clicks (or taps) any option of the mobile menu, the mobile menu disappear.

Please ensure that the requirements are followed, using JavaScript code for this.

2022-04-21 14:29 UTC, merged